### ISSUE TITLE
How to add ndisasm.exe to PATH?

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [ilammy/setup-nasm#29]
I'm using ndisasm in my batch file, why it wasn't added to the PATH variable? 

Last stable version of NASM includes that
![image](https://user-images.githubusercontent.com/109800286/193409580-e31a21ad-e8fc-4bc2-a287-8f9152c8b989.png)

```yaml
name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/setup-nasm@v1

      - name: Build project
        run: build.bat
        shell: cmd
```

```
'ndisasm' is not recognized as an internal or external command, operable program or batch file.
```
